version: '2'
services:

  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./lib:/package/lib
      - ./src:/package/src
      - ./tests:/package/tests
      - ./.babelrc:/package/.babelrc
      - ./GRPCEventStore.proto:/package/GRPCEventStore.proto
      - ./package.json:/package/package.json

  cockroach:
    image: cockroachdb/cockroach:beta-20161103
    ports:
      - "8080:8080"
      - "26257:26257"
    command: start --insecure
