FROM mhart/alpine-node:6.3

WORKDIR /package

# Install dumb-init
RUN apk add --no-cache build-base py-pip libc6-compat \
      && pip install dumb-init \
      && apk del build-base \
      && rm -rf /var/cache/apk/*

# Install dependencies
ADD package.json /package/package.json
RUN npm install
